spring.application.name=reactive-paradigm-capstone

spring.mongodb.uri=mongodb://root:pwd@localhost:27017/admin?authSource=admin

services.order-search.base-url=http://localhost:8081
services.product-info.base-url=http://localhost:8082

server.port=8080
